sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$TRAVIS_BUILD_DIR/vendor/bin"

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=3.7.11
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.3
      env: WP_VERSION=latest

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer require wp-cli/wp-cli:dev-master
  - composer install
  - bash bin/install-package-tests.sh

before_script:
  - composer validate

script:
  - bash bin/test.sh
